version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    
    #初回`docker-compose up`後、
    #docker-compose run app rails new . --force --database=mysql --skip-bundle
    #docker-compose run app rake db:create
    
    #bundleinstall後のサーバー立ち上げ
    #command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb

    ports:
      - '3000:3000'
    volumes:
      - /var/tmp
      - .:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password

volumes:
  db_data:
  bundle_path: